resource = {
    listOrder: 'Danh sách đơn hàng', 
    shopName: 'Tên Shop',
    numberProduct: 'Số sản phẩm',
    moneyProduct: 'Tiền hàng',
    actions: 'Thao tác',
    color: 'Màu',
    size: 'Size',
    deleteProduct: 'Xóa',
    depositOrder: ' Đặt cọc đơn',
    unit: 'vnd',
    employeeContent: 'Nhân viên LikeOrder.com sẽ không thấy',
    employeePlaceholder: 'Ghi chú riêng tư',
    noteCustomer: 'Ghi chú đơn hàng',
    notePlaceholder: 'Viết ghi chú cho LikeOrder.com',
    noteProductPlaceholder: 'Ghi chú sản phẩm',
    selectAll: 'Chọn tất cả',
    totalOrder: 'Tổng đơn',
    totalLink: 'Tổng Link',
    totalProduct: 'Tổng số sản phẩm',
    deposit: 'Đặt cọc',
    totalMoney: 'Tổng tiền',
    order: 'đơn',
    noteNoneOrder: '"Rất tiếc, giỏ mua hàng của bạn hiện không có sản phẩm nào, hãy nhanh chóng đặt hàng ngay" Bạn có thể:',
    orderNow: 'Đặt hàng ngay bây giờ',
    accountComeback: 'Trở lại trang cá nhân',
    deleteall: 'Xóa toàn bộ'

}