resource = {
    listOrder: 'รายชื่อออเดอร์',
    shopName: 'ชื่อร้านค้า',
    numberProduct: 'จำนวนสินค้า',
    moneyProduct: 'จำนวนเงินสินค้า',
    actions: 'การยักย้าย',
    color: 'สี',
    size: 'ขนาด',
    deleteProduct: 'ลบ',
    depositOrder: ' มัดจำ',
    unit: 'baht',
    employeeContent: 'พนักงานlikeorder.comจะไม่เห็นข้อความตรงนี้',
    employeePlaceholder: 'บันทึกส่วนตัว',
    noteCustomer: 'หมายเหตุการสั่งซื้อ',
    notePlaceholder: 'เขียนบันทึกเพื่อ LikeOrder.com',
    noteProductPlaceholder: 'หมายเหตุผลิตภัณฑ์',
    selectAll: 'เลือกทั้งหมด', 
    totalOrder: 'จำนวนออเดอร์ทั้งหมด',
    totalLink: 'จำนวนลิ้งค์ทั้งหมด',
    totalProduct: 'จำนวนสินค้าทั้งหมด',
    deposit: 'มัดจำ',
    totalMoney: 'จำนวนเงินทั้งหมด',
    order: 'เดียว',
    noteNoneOrder: '"ขอโทษรถเข็นของคุณไม่ว่างได้อย่างรวดเร็วสั่งซื้อตอนนี้" คุณสามารถ:',
    orderNow: 'สั่งซื้อตอนนี้',
    accountComeback: 'กลับไปยังโปรไฟล์',
    deleteall: 'ยกเลิกทั้งหมด'
}