statusApp = {

    // Trạng thái đơn hàng Order
    orderPackage: [
        { Name: "Chinese shops sending goods", Class: "label label-default", Ifa: "fa fa-file-o bg-gray" },
        { Name: "Kho TQ nhận hàng", Class: "label label-warning", Ifa: "fa fa-clock-o bg-yellow" },
        { Name: "Đang trong kho TQ", Class: "label label-warning", Ifa: "fa fa-calendar-check-o bg-blue" },
        { Name: "Xuất kho TQ", Class: "label label-info", Ifa: "fa fa-exclamation-triangle bg-yellow" },
        { Name: "Trên đường về VN", Class: "label label-warning", Ifa: "fa fa-cart-plus bg-gray" },
        { Name: "Nhận hàng", Class: "label label-warning", Ifa: "fa fa-cart-arrow-down bg-yellow" },
        { Name: "Trong kho", Class: "label label-warning", Ifa: "fa fa-exclamation-triangle bg-yellow" },
        { Name: "Đang điều chuyển", Class: "label label-warning", Ifa: "fa fa-cc-visa bg-yellow" },
        { Name: "Chờ giao hàng", Class: "label label-success", Ifa: "fa fa-check-circle-o bg-green" },
        { Name: "Đang đi giao hàng", Class: "label label-primary", Ifa: "fa fa-archive bg-blue" },
        { Name: "Đã trả hàng", Class: "label label-success", Ifa: "fa fa-cubes bg-yellow" },
        { Name: "Hàng bị mất", Class: "label label-danger", Ifa: "fa fa-truck bg-aqua" },
        { Name: "Hàng bị mất mã", Class: "label label-danger", Ifa: "fa fa-truck bg-yellow" },
        { Name: "Hàng bị mất đã xử lý", Class: "label label-danger", Ifa: "fa fa-home bg-green" }
    ],
    // Trạng thái đơn hàng Order
    orderPackageView: [
        { Name: "Chinese shops sending goods", Class: "label label-default", Ifa: "fa fa-file-o bg-gray" },
        { Name: "Kho TQ nhận hàng", Class: "label label-warning", Ifa: "fa fa-clock-o bg-yellow" },
        { Name: "Đang trong kho TQ", Class: "label label-warning", Ifa: "fa fa-calendar-check-o bg-blue" },
        { Name: "Xuất kho TQ", Class: "label label-warning", Ifa: "fa fa-exclamation-triangle bg-yellow" },
        { Name: "Trên đường về VN", Class: "label label-info", Ifa: "fa fa-cart-plus bg-gray" },
        { Name: "Trên đường về VN", Class: "label label-info", Ifa: "fa fa-cart-arrow-down bg-yellow" },
        { Name: "Trong kho VN", Class: "label label-info", Ifa: "fa fa-exclamation-triangle bg-yellow" },
        { Name: "Đang điều chuyển", Class: "label label-info", Ifa: "fa fa-cc-visa bg-yellow" },
        { Name: "Chờ giao hàng", Class: "label label-primary", Ifa: "fa fa-check-circle-o bg-green" },
        { Name: "Đang đi giao hàng", Class: "label label-primary", Ifa: "fa fa-archive bg-blue" },
        { Name: "Đã trả hàng", Class: "label label-success", Ifa: "fa fa-cubes bg-yellow" },
        { Name: "Hàng bị mất", Class: "label label-danger", Ifa: "fa fa-truck bg-aqua" },
        { Name: "Hàng bị mất", Class: "label label-danger", Ifa: "fa fa-truck bg-yellow" },
        { Name: "Hàng bị mất", Class: "label label-danger", Ifa: "fa fa-home bg-green" }
    ],
    complain: [
        { Name: "Chờ xử lý", Key: "", Class: "label label-default" },
        { Name: "Đang xử lý", Key: "", Class: "label label-warning" },
        { Name: "Chờ đặt hàng xử lý", Key: "", Class: "label label-warning" },
        { Name: "Chờ CSKH xử lý", Key: "", Class: "label label-warning" },
        { Name: "Chờ phê duyệt", Key: "", Class: "label label-warning" },
        { Name: "Chờ kế toán xử lý", Key: "", Class: "label label-warning" },
        { Name: "Kế toán đã hoàn tiền", Class: "label label-success" },
        { Name: "Hoàn thành", Key: "", Class: "label label-success" },
        { Name: "Đã hủy", Key: "", Class: "label label-danger" },
    ],
    complainView: [
        { Name: "Chờ xử lý", Key: "", Class: "label label-default" },
        { Name: "Đang xử lý", Key: "", Class: "label label-warning" },
        { Name: "Đang xử lý", Key: "", Class: "label label-warning" },
        { Name: "Đang xử lý", Key: "", Class: "label label-warning" },
        { Name: "Đang xử lý", Key: "", Class: "label label-warning" },
        { Name: "Đang xử lý", Key: "", Class: "label label-warning" },
        { Name: "Kế toán đã hoàn tiền", Class: "label label-success" },
        { Name: "Hoàn thành", Key: "", Class: "label label-success" },
        { Name: "Đã hủy", Key: "", Class: "label label-danger" },
    ],
    source: [
        { Name: "Chờ xử lý", Key: "", Class: "label label-default" },
        { Name: "Đang xử lý", Key: "", Class: "label label-warning" },
        { Name: "Chờ khách chọn NCC", Key: "", Class: "label label-warning" },
        { Name: "Hoàn thành", Key: "", Class: "label label-success" },
        { Name: "Đã hủy", Key: "", Class: "label label-danger" },
    ],
    deposit: [
        { Name: "Chờ báo giá", Key: "WaitDeposit", Value: 0 },
        { Name: "Chờ xử lý", Key: "Processing", Value: 1 },
        { Name: "Chờ xử lý", Key: "PendingPrice", Value: 2 },
        { Name: "Chờ kết đơn", Key: "WaitOrder", Value: 3 },
        { Name: "Chờ hàng về kho", Key: "Order", Value: 4 },
        { Name: "Hàng trong kho", Key: "InWarehouse", Value: 5 },
        { Name: "Đang vận chuyển", Key: "Shipping", Value: 6 },
        { Name: "Chờ giao hàng", Key: "Pending", Value: 7 },
        { Name: "Giao hàng thành công", Key: "PendingSuccess", Value: 8 },
        { Name: "Hoàn thành", Key: "Finish", Value: 9 },
        { Name: "Hủy", Key: "Cancel", Value: 10 },
    ],
    order: [
        { Name: "Mới", Key: "New", Value: 0 },
        { Name: "Chờ báo giá", Key: "WaitPrice", Value: 1 },
        { Name: "Đang báo giá", Key: "AreQuotes", Value: 2 },
        { Name: "Chờ đặt cọc", Key: "WaitDeposit", Value: 3 },
        { Name: "Chờ đặt hàng", Key: "WaitOrder", Value: 4 },
        { Name: "Đang đặt hàng", Key: "Order", Value: 5 },
        { Name: "Chờ kế toán thanh toán", Key: "WaitAccountant", Value: 6 },
        { Name: "Kế toán đang thanh toán", Key: "AccountantProcessing", Value: 7 },
        { Name: "Đặt hàng xong", Key: "OrderSuccess", Value: 8 },
        { Name: "Shop phát hàng", Key: "DeliveryShop", Value: 9 },
        { Name: "Nhận hàng", Key: "InWarehouse", Value: 10 },
        { Name: "Đang vận chuyển", Key: "Shipping", Value: 11 },
        { Name: "Chờ giao hàng", Key: "Pending", Value: 12 },
        { Name: "Đang thành công", Key: "PendingSuccess", Value: 13 },
        { Name: "Hoàn thành", Key: "Finish", Value: 14 },
        { Name: "Hủy", Key: "Cancel", Value: 15 },
        { Name: "Hỏng mất", Key: "Lost", Value: 16 },
    ],
    OrderServices: [
        { Name: "Phí dịch vụ mua hàng", Key: "Order", Value: 0 },
        { Name: "Phí dịch vụ kiểm đếm", Key: "Audit", Value: 1 },
        { Name: "Phí dịch vụ đóng kiện", Key: "Packing", Value: 2 },
        { Name: "Phí Shop vận chuyển", Key: "ShopShipping", Value: 3 },
        { Name: "Phí dịch vụ chuyển hàng về Việt Nam", Key: "OutSideShipping", Value: 4 },
        { Name: "Phí dịch vụ giao hàng tại nhà", Key: "InSideShipping", Value: 5 },
        { Name: "Phí dịch vụ vận chuyển nhanh (đường hàng không)", Key: "FastDelivery", Value: 6 },
        { Name: "Phí dịch phát sinh", Key: "Other", Value: 7 },
        { Name: "Phí đóng bao", Key: "PackingCharge", Value: 8 },
    ],
    // Trạng thái đơn hàng Order
    orderView: [
        { Name: "", Class: "label label-default", Ifa: "fa fa-file-o bg-gray" },
        { Name: "Chờ báo giá", Class: "label label-default", Ifa: "fa fa-clock-o bg-yellow" },
        { Name: "Chờ báo giá", Class: "label label-default", Ifa: "fa fa-calendar-check-o bg-blue" },
        { Name: "Chờ đặt cọc", Class: "label label-chodatcoc", Ifa: "fa fa-exclamation-triangle bg-yellow" },
        { Name: "Chờ đặt hàng", Class: "label label-orangered", Ifa: "fa fa-cart-plus bg-gray" },
        { Name: "Đang đặt hàng", Class: "label label-warning", Ifa: "fa fa-cart-arrow-down bg-yellow" },
        { Name: "Đang đặt hàng", Class: "label label-warning", Ifa: "fa fa-exclamation-triangle bg-yellow" },
        { Name: "Đang đặt hàng", Class: "label label-warning", Ifa: "fa fa-cc-visa bg-yellow" },
        { Name: "Đặt hàng xong", Class: "label label-success", Ifa: "fa fa-check-circle-o bg-green" },
        { Name: "Shop phát hàng", Class: "label label-primary", Ifa: "fa fa-archive bg-blue" },
        { Name: "NHKD nhận hàng", Class: "label label-nhkd", Ifa: "fa fa-cubes bg-yellow" },
        { Name: "Đang vận chuyển", Class: "label label-info", Ifa: "fa fa-truck bg-aqua" },
        { Name: "Chờ giao hàng", Class: "label label-info", Ifa: "fa fa-truck bg-yellow" },
        { Name: "Đang giao hàng", Class: "label label-dgh", Ifa: "fa fa-home bg-green" },
        { Name: "Hoàn thành", Class: "label label-success", Ifa: "fa fa-check bg-aqua" },
        { Name: "Hủy", Class: "label label-danger", Ifa: "fa fa-times-circle bg-red" },
        { Name: "Hỏng mất", Class: "label label-danger2", Ifa: "fa user-times bg-red" }
    ],
    // Tạng thái đơn hàng ký gửi
    depositView: [
        { Name: "Chờ báo giá", Class: "label label-default" },
        { Name: "Chờ xử lý", Class: "label label-warning" },
        { Name: "Chờ xử lý", Class: "label label-warning" },
        { Name: "Chờ kết đơn", Class: "label label-primary" },
        { Name: "Chờ hàng về kho", Class: "label label-orangered" },
        { Name: "Hàng trong kho", Class: "label label-info" },
        { Name: "Đang vận chuyển", Class: "label label-transport" },
        { Name: "Chờ giao hàng", Class: "label label-info" },
        { Name: "Đang giao hàng", Class: "label label-green" },
        { Name: "Hoàn thành", Class: "label label-success" },
        { Name: "Hủy", Class: "label label-danger" }
    ],
}